### ISSUE TITLE
Add your favorite cheat sheet under each language category

### ISSUE THREAD

**Issue by PandiyanCool** [PandiyanCool/CheatSheet#2]
Feel free to create new language category based on needs. (follow alphabetical order)

Try to add only latest cheat sheet. Make sure not adding any outdated sheets.

Add a comment which one you are picking. So we can avoid more people working on same category.

If possible give a star ⭐️ 

#Peace

**Comment by Danushka96** [comment]
I will work on VueJs Cheat Sheet.

**Comment by PandiyanCool** [comment]
Sure @Danushka96
